default_language_version:
  python: python3.12
repos: []
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-added-large-files
  #     - id: detect-private-key
  #     - id: check-merge-conflict
  #     - id: check-symlinks
  #     - id: requirements-txt-fixer

  # - repo: https://github.com/myint/autoflake
  #   rev: v2.3.1
  #   hooks:
  #     - id: autoflake
  #       exclude: .*/__init__.py
  #       args:
  #         - --in-place
  #         - --remove-all-unused-imports
  #         - --expand-star-imports
  #         - --remove-duplicate-keys
  #         - --remove-unused-variables

  # - repo: https://github.com/pycqa/flake8.git
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8

  # - repo: https://github.com/pre-commit/mirrors-isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.17.0
  #   hooks:
  #     - id: mypy

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer

  # - repo: https://github.com/ambv/black
  #   rev: 24.3.0
  #   hooks:
  #     - id: black
  #       language_version: python3.12

  # - repo: https://github.com/pycqa/pylint
  #   rev: v3.3.5
  #   hooks:
  #     - id: pylint

  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.39.0
  #   hooks:
  #     - id: markdownlint
  #       args: [--fix]
